### ISSUE TITLE
Won't install

### ISSUE THREAD

**Issue by danielbayley** [ericfreese/font-viewer#7]
Installing font-viewer to /Users/Dan/Library/Application Support/Atom/packages ✗

> freetype2@0.2.3 install /private/var/folders/rg/4lc94q1x1_xd89qsnjdkgsjw0000gn/T/apm-install-dir-115923-61581-hs5w6j/node_modules/font-viewer/node_modules/freetype2
> node-gyp rebuild

make: *** No rule to make target `../../../../../../../../../../../../Users/Dan/Library/Application', needed by `Makefile'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/rg/4lc94q1x1_xd89qsnjdkgsjw0000gn/T/apm-install-dir-115923-61581-hs5w6j/node_modules/font-viewer/node_modules/freetype2
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Darwin 15.0.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/Dan/Library/Application Support/Atom/.apm/.apmrc" "--userconfig" "/Users/Dan/Library/Application Support/Atom/.apmrc" "install" "/private/var/folders/rg/4lc94q1x1_xd89qsnjdkgsjw0000gn/T/d-115923-61581-lpn6k4/package.tgz" "--target=0.30.7" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! freetype2@0.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the freetype2@0.2.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the freetype2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls freetype2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/rg/4lc94q1x1_xd89qsnjdkgsjw0000gn/T/apm-install-dir-115923-61581-hs5w6j/npm-debug.log

**Comment by ericfreese** [comment]
Are you still having this issue? I'm not seeing a problem using Atom 1.3.2 on Mac OS 10.10.

According to your log, it looks like it's trying to install an old version (0.2.3) of the freetype2 library, instead of the most recent 0.3.0 version, which is why it failed.

Try again and let me know if it's still failing.

**Comment by ericfreese** [comment]
Nevermind, there was a problem with the plugin specifying an old version of freetype2.

Should be fixed with version 0.3.1.

**Comment by danielbayley** [comment]
I still can't install it unfortunately. This is the error log…

Installing “font-viewer@0.3.1” failed.Hide output…

> freetype2@0.3.0 install /private/var/folders/rg/4lc94q1x1_xd89qsnjdkgsjw0000gn/T/apm-install-dir-11629-82750-n4e4sc/node_modules/font-viewer/node_modules/freetype2
> node-gyp rebuild


make: *** No rule to make target `../../../../../../../../../../../../Users/Dan/Library/Application', needed by `Makefile'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/rg/4lc94q1x1_xd89qsnjdkgsjw0000gn/T/apm-install-dir-11629-82750-n4e4sc/node_modules/font-viewer/node_modules/freetype2
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Darwin 15.3.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/Dan/Library/Application Support/Atom/.apm/.apmrc" "--userconfig" "/Users/Dan/Library/Application Support/Atom/.apmrc" "install" "/private/var/folders/rg/4lc94q1x1_xd89qsnjdkgsjw0000gn/T/d-11629-82750-vfhm9t/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! freetype2@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the freetype2@0.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the freetype2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls freetype2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/rg/4lc94q1x1_xd89qsnjdkgsjw0000gn/T/apm-install-dir-11629-82750-n4e4sc/npm-debug.log
